name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:18-alpine3.14
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release