name: Shell Commands

on: [push]

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # Maximum number of minutes your job can take
    steps:
      - name: echo a string
        run: eccho "Hello World"
        continue-on-error: true
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python Commands
        run: |
          import platform
          print (platform.processor())
        shell: python
  run-another-shell-command:
    runs-on: ubuntu-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory
        run: pwd